platform :ios, '12.0'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

flipperkit_version = '0.23.6'

target 'yeet' do

#  use_modular_headers!

  pod "SnapSDK/SCSDKCreativeKit", modular_headers: true
  pod 'XExtensionItem', modular_headers: true
  # Pods for yeet
    pod 'FBLazyVector', path: '../node_modules/react-native/Libraries/FBLazyVector', modular_headers: false
    pod 'FBReactNativeSpec', path: '../node_modules/react-native/Libraries/FBReactNativeSpec', modular_headers: false
    pod 'RCTRequired', path: '../node_modules/react-native/Libraries/RCTRequired', modular_headers: false
    pod 'RCTTypeSafety', path: '../node_modules/react-native/Libraries/TypeSafety', modular_headers: false
    pod 'React', path: '../node_modules/react-native/', modular_headers: true
    pod 'React-Core', path: '../node_modules/react-native/', modular_headers: true
    pod 'React-CoreModules', path: '../node_modules/react-native/React/CoreModules', modular_headers: false
    pod 'React-Core/DevSupport', path: '../node_modules/react-native/', modular_headers: false
    pod 'React-RCTActionSheet', path: '../node_modules/react-native/Libraries/ActionSheetIOS', modular_headers: false
    pod 'React-RCTAnimation', path: '../node_modules/react-native/Libraries/NativeAnimation', modular_headers: false
    pod 'React-RCTBlob', path: '../node_modules/react-native/Libraries/Blob', modular_headers: false
    pod 'React-RCTImage', path: '../node_modules/react-native/Libraries/Image', modular_headers: false
    pod 'React-RCTLinking', path: '../node_modules/react-native/Libraries/LinkingIOS', modular_headers: false
    pod 'React-RCTNetwork', path: '../node_modules/react-native/Libraries/Network', modular_headers: false
    pod 'React-RCTSettings', path: '../node_modules/react-native/Libraries/Settings', modular_headers: false
    pod 'React-RCTText', path: '../node_modules/react-native/Libraries/Text', modular_headers: false
    pod 'React-RCTSettings', path: '../node_modules/react-native/Libraries/Settings', modular_headers: false
    pod 'React-RCTVibration', path: '../node_modules/react-native/Libraries/Vibration', modular_headers: false
    pod 'React-Core/RCTWebSocket', path: '../node_modules/react-native/', modular_headers: false
    pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
    pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
    pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
    pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
    pod 'ReactCommon/jscallinvoker', :path => "../node_modules/react-native/ReactCommon"
    pod 'ReactCommon/turbomodule/core', :path => "../node_modules/react-native/ReactCommon"
    pod 'Yoga', path: '../node_modules/react-native/ReactCommon/yoga', modular_headers: false
    pod 'PanModal', git: 'https://github.com/KyoheiG3/PanModal.git', branch: 'fix-background-dimming-animation'

    pod 'IQKeyboardManagerSwift'
  pod 'DoubleConversion',
      podspec:
        '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec',
      modular_headers: false
  pod 'glog',
      podspec: '../node_modules/react-native/third-party-podspecs/glog.podspec',
      modular_headers: false
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  pod 'ColorSlider', git: "https://github.com/Jarred-Sumner/ColorSlider.git", modular_headers: true

  pod 'SBObjectiveCWrapper',
      git: 'https://github.com/SwiftyBeaver/SBObjectiveCWrapper.git', modular_headers: true

  # pod 'FlipperKit', "~> #{flipperkit_version}"
  # pod 'FlipperKit/SKIOSNetworkPlugin', "~> #{flipperkit_version}"
  # pod 'FlipperKit/FlipperKitUserDefaultsPlugin', "~> #{flipperkit_version}"
  # pod 'FlipperKit/FlipperKitLayoutPlugin', "~> #{flipperkit_version}"




  pod 'SDWebImageWebPCoder', modular_headers: true
  pod 'SDWebImage', '5.1.1', modular_headers: true
  pod 'SDWebImagePhotosPlugin', modular_headers: true
  pod 'SwiftyJSON', '~> 4.0', modular_headers: true
  pod 'UIImageColors', modular_headers: true
  pod 'DVAssetLoaderDelegate', modular_headers: true
  pod 'SwiftyTimer', modular_headers: true
  pod 'KTVHTTPCache', '~> 2.0.0', modular_headers: true
  pod 'MulticastDelegateSwift', modular_headers: true
  pod 'Promises', modular_headers: true

  pod 'PINCache', git: 'https://github.com/pinterest/PINCache.git', modular_headers: true
  pod 'PINRemoteImage',
      modular_headers: true,
      git: 'https://github.com/pinterest/PINRemoteImage.git'
  pod 'PINRemoteImage/WebP',
      modular_headers: true,
      git: 'https://github.com/pinterest/PINRemoteImage.git'
  pod 'libwebp', modular_headers: true
  pod 'VFCabbage', modular_headers: true
  pod 'NextLevelSessionExporter', modular_headers: false

  pod 'SwiftyBeaver', modular_headers: true

  pod 'RNDeviceInfo',
      path: '../node_modules/react-native-device-info', modular_headers: false

  pod 'BVLinearGradient',
      path: '../node_modules/react-native-linear-gradient',
      modular_headers: false

  pod 'react-native-video',
      path: '../node_modules/react-native-video', modular_headers: false

  pod 'react-native-image-picker',
      path: '../node_modules/react-native-image-picker', modular_headers: false

  pod 'rn-fetch-blob',
      path: '../node_modules/rn-fetch-blob', modular_headers: false

  pod 'RNReactNativeHapticFeedback',
      path: '../node_modules/react-native-haptic-feedback',
      modular_headers: false

  pod 'RNSecureKeyStore',
      path: '../node_modules/react-native-secure-key-store/ios',
      modular_headers: false


      pod 'OpenCV2'

  pod 'MMKV'

  pod 'RNFS', path: '../node_modules/react-native-fs', modular_headers: false

  # pod 'react-native-photos-framework', :path => '../node_modules//react-native-photos-framework'

  pod 'RNGestureHandler',
      path: '../node_modules/react-native-gesture-handler',
      modular_headers: false

  pod 'RNReanimated',
      path: '../node_modules/react-native-reanimated', modular_headers: false


  pod 'react-native-config',
      path: '../node_modules/react-native-config', modular_headers: false

  pod 'react-native-cronet',
      path: '../node_modules/react-native-cronet', modular_headers: false

  pod 'RNFastImage',
      path: '../node_modules/react-native-fast-image', modular_headers: false

  pod 'RNSharedElement', path: '../node_modules/react-native-shared-element'

  pod 'RNFBAnalytics', path: '../node_modules/@react-native-firebase/analytics'
  pod 'GoogleIDFASupport', '~> 3.14.0', modular_headers: true


  # pod 'appcenter', :path => '../node_modules/appcenter'
  # pod 'appcenter-analytics', :path => '../node_modules/appcenter-analytics'

  pod 'CodePush', path: '../node_modules/react-native-code-push', modular_headers: true

  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'JGProgressHUD', modular_headers: true

  pod 'Permission-Contacts', :path => "#{permissions_path}/Contacts.podspec"
  pod 'Permission-LocationAlways', :path => "#{permissions_path}/LocationAlways.podspec"
  pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse.podspec"
  pod 'Permission-MediaLibrary', :path => "#{permissions_path}/MediaLibrary.podspec"
  pod 'Permission-Notifications', :path => "#{permissions_path}/Notifications.podspec"
  pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary.podspec"

  pod 'SwiftyImageIO', modular_headers: true
  pod 'RNFBApp', :path => '../node_modules/@react-native-firebase/app', modular_headers: true


  pod 'react-native-cameraroll', :path => '../node_modules/@react-native-community/cameraroll', modular_headers: true



  use_native_modules!
  pod 'RealmJS', :path => '../node_modules/realm'

  target 'yeetTests' do
    inherit! :search_paths

    pod 'Quick', modular_headers: false
    pod 'Nimble',
        modular_headers: true, git: 'https://github.com/Quick/Nimble.git'
  end
end

target 'OneSignalNotificationServiceExtension' do
  pod 'OneSignal', '>= 2.9.3', '< 3.0'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == 'YogaKit'
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '4.1'
      end
    elsif target.name == 'react-native-config'
      phase =
        target.project.new(Xcodeproj::Project::Object::PBXShellScriptBuildPhase)
      phase.shell_script =
        'cd ../../' \
          ' && RNC_ROOT=./node_modules/react-native-config/' \
          ' && export SYMROOT=$RNC_ROOT/ios/ReactNativeConfig' \
          ' && export BUILD_DIR=$RNC_ROOT/ios/ReactNativeConfig' \
          ' && ruby $RNC_ROOT/ios/ReactNativeConfig/BuildDotenvConfig.ruby'

      target.build_phases << phase
      target.build_phases.move(phase, 0)
    end
  end
  file_name = Dir.glob('*.xcodeproj')[0]
  app_project = Xcodeproj::Project.open(file_name)
  app_project.native_targets.each do |target|
    target.build_configurations.each do |config|
      cflags = config.build_settings['OTHER_CFLAGS'] || '$(inherited) '
      unless cflags.include? '-DFB_SONARKIT_ENABLED=1'
        puts 'Adding -DFB_SONARKIT_ENABLED=1 in OTHER_CFLAGS...'
        cflags << '-DFB_SONARKIT_ENABLED=1'
      end
      config.build_settings['OTHER_CFLAGS'] = cflags
    end
    app_project.save
  end
  installer.pods_project.save
end
